safe: true
lsi: false

port: 5555

encoding: utf-8

exclude: ['public', 'Gemfile', 'Gemfile.lock', 'Procfile', 'unicorn.rb', 'config.ru', 'src', 'Cakefile', 'style.less', 'vendor']



destination: 'public'
sass:
    sass_dir: _sass
    style: :compressed


